[package]
name = "vulkan-rs"
version = "0.1.0"
authors = ["Emirhan Taşdeviren <emirhan.tasdeviren@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raw-window-handle = "0.3"
